eval "$(zellij setup --generate-auto-start zsh)" # Al prinici perque va mes rapid
# Lines configured by zsh-newuser-install
SAVEHIST=100000
HISTSIZE=100000
HISTFILE=~/.cache/zsh/history
setopt autocd
bindkey -v
# End of lines configured by zsh-newuser-install
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)		
set HIST_FIND_NO_DUPS
setopt hist_FIND_NO_DUPS
set histignorealldups
setopt histignorealldups

#Beginning of lines added be me
export VISUAL=nvim
export EDITOR="$VISUAL"
autoload -U colors && colors
PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b " # Irrelevant with starship, but I liked it

zstyle ':completion:*' list-colors 'di=1;35:ln=35:so=32:pi=33:ex=31:bd=46;34:cd=43;34:su=41;30:sg=30:tw=30:ow=30'

function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
}
# preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.
_fix_cursor() {
   echo -ne '\e[1 q'
}

precmd_functions+=(_fix_cursor)

autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

precmd_functions+=(_fix_cursor)

# Load aliases if existent.
[ -f "$HOME/.shell_aliases" ] && source "$HOME/.shell_aliases"

#Disabled, starship takes it over
#function zle-line-init zle-keymap-select {
#    RPS1="${${KEYMAP/vicmd/- NORM -}/(main|viins)/- INS -}"
#    RPS2=$RPS1
#    zle reset-prompt
#}

zle -N zle-line-init

#zstyle ':completion:*' '' matcher-list 'm:{a-z}={A-Z}'
#source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.nix-profile/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.nix-profile/share/zsh-autosuggestions
source ~/.nix-profile/share/zsh-autocomplete
export PATH=$PATH:$HOME/.local/bin:$HOME/.local/share/gem/ruby/3.0.0/bin

export GEM_HOME=$HOME/gems
export PATH=$HOME/gems/bin:$PATH

export DWM_LOGS_LOCATION="/media/HDD/logs/dwm"

#source ~/.zsh_envvars

[[ $- != *i* ]] && return
#Si zellij no esta executat, executa'l:
#[[ -z "$TMUX" ]] && exec tmux # Deprecated by me, no longer using tmux
setopt histignorespace
#[ $(echo -e "Random\nDefault\nStandard" | dmenu -i -p "$1") ]

. /etc/nixos/scripts/dircolors.sh # Load in ls colors


eval "$(zoxide init zsh)"
eval "$(starship init zsh)"

#End of lines added by me



[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env" # ghcup-env
