[lispt]
source = "lispt"
should_replace_name = true

[LaTeX]
source = "latex"
should_replace_name = true

[C]
source = "C"
should_replace_name = true

[AdventOfCode]
source = "AdventOfCodeDay"
should_replace_name = true

[copet-rust]
source = "copet-rust"
should_replace_name = true

[copet-haskell]
source = "copet-haskell"
should_replace_name = true

[copet-cpp]
source = "copet-cpp"
should_replace_name = true
