#!/bin/sh
NOTIFTEXT="Guardat a ~/.scrot/$(date +%y-%m-%d_%H:%M)"

function send_successful_notification() {
    notify-send -t 10000 "Screenshot fet" "$NOTIFITEXT"
}

function send_error_notification() {
    notify-send -t 5000 "Screenshot - ERROR" "Hi ha hagut un error"
}

maim -s -u | xclip -selection clipboard -t image/png -i 

