#!/run/current-system/sw/bin/lua

get_output = function(cmd)
   local handle = io.popen(cmd)
   local output = handle:read("*a")
   return output
end

local curr_command = "free -h --si | awk 'FNR == 2 { print $3 }'"
local total_command = "free -h --si | awk 'FNR == 2 { print $2 }'"

local current = get_output(curr_command)
local total = get_output(total_command)

print("<b>"
      .. string.gsub(string.gsub(current, "\n", ""), "G", "")
      .. "</b>"
      .. "G"
      .. "/"
      .. string.gsub(total, "\n", "")
)
