#!/usr/bin/env lua

get_output = function(cmd)
   local handle = io.popen(cmd)
   local output = handle:read("*a")
   return output
end

local cmds = {
   ["curr"] =  "free -h --si | awk 'FNR == 2 { print $3 }'",
   ["total"] = "free -h --si | awk 'FNR == 2 { print $2 }'",
}

local outputs = {}
for name, cmd in pairs(cmds) do outputs[name] = get_output(cmd) end

print("<b>"
      .. string.gsub(string.gsub(outputs["curr"], "\n", ""), "G", "")
      .. "</b>"
      .. "G"
      .. "/"
      .. string.gsub(outputs["total"], "\n", "")
)
