#!/bin/sh

MAX_BRIGHTNESS=15
BRIGHTNESS_OFFSET=3/2 #Solution for MAX_BRIGHTNESS/x = 10, since 10 is 100/10 (usual max and offset)
case $1 in
    2) echo $((100 * $(/usr/bin/cat /sys/class/backlight/acpi_video0/actual_brightness) / $MAX_BRIGHTNESS ))%;;
    1) echo $(($(/usr/bin/cat /sys/class/backlight/acpi_video0/actual_brightness)+$BRIGHTNESS_OFFSET)) > /sys/class/backlight/acpi_video0/brightness && pkill -RTMIN+4 dwmblocks || notify-send "An error ocurred" ;; # Increase brightness
    0) echo $(($(/usr/bin/cat /sys/class/backlight/acpi_video0/actual_brightness)-$BRIGHTNESS_OFFSET)) > /sys/class/backlight/acpi_video0/brightness && pkill -RTMIN+4 dwmblocks || notify-send "An error ocurred" ;; # Decrease brightness
    "") echo "You forgot the argument"
esac
