#!/bin/bash

LIST="Master Headphone Front"

if amixer sget Master | grep '\[off\]' > /dev/null ; then
        CMD=unmute
else
        CMD=mute
fi

#for CONTROL in $LIST ; do
#        amixer -q sset $CONTROL $CMD
#done
 
#amixer -q sset  Master $CMD
amixer -D pulse set Master Playback Switch toggle
