#!/bin/sh

#This script is called on startup to remap keys
setxkbmap es

setxkbmap -option caps:swapescape

setxkbmap -option compose:menu # Set dumb right-click key to the useful compose key

#xmodmap -e "keycode 9 = NoSymbol" # Disable 'Esc' key fully
xset r rate 300 50
