#!/bin/sh 

while :
do
	#Date (for tracking)
	date 
	#coretemp-isa-0000 (Adapter: ISA adapter)
	echo -e "#--\n#Core:"
	sensors | tail -n 19 | head -n 9 | awk '{NF-=6};1'
	
	#acpitz-acpi-0 (Adapter: ACPI interface)
	echo -e "#--\n#Acpi"
	sensors | tail -n 7 | head -n 1 | awk '{NF-=3};1'
	
	#nvme-pci-0100 (Adapter: PCI adapter)
	echo -e "#--\n#Nvme"
	sensors |tail -n 3 | head -n1 | awk '{NF-=6};1'
	
	#End
	echo -e "\n" 
	sleep 600 # 5 minute
done
