#!/bin/bash

function mute_notify () {
notify-send --icon="$HOME/scripts/images/speaker.png" -t 4000 --urgency normal "Audio Status" "Audio Muted" && echo "muted" && pkill -RTMIN+5 dwmblocks
}

function unmute_notify () {
notify-send --icon="$HOME/scripts/images/speaker.png" -t 4000  --urgency critical "Audio Status" "Audio Unmuted" && echo "unmuted" && pkill -RTMIN+5 dwmblocks
}

function display_muted () {
    amixer sget Master | grep "Front.*:" | awk -F" " '{print $5 " (M)"}' | tail -n1 | sed -e 's/\[//' -e 's/\]//'
}

function display_unmuted () {
    amixer sget Master | grep "Front.*:" | awk -F" " '{print $5}' | tail -n1 | sed -e 's/\[//' -e 's/\]//'
}

STATUS=$(amixer)
case $1 in
	# 2) awk -F"[][]" '/]/ { print $2 }' <(amixer sget Master);; #Output current volume levels with Mono Device
	2) amixer sget Master | awk -F"[][]" '/]/ { print $2 }' | head -n1  ;; #Output current volume levels with Mono Device
    #2) grep "\[off\]" <<< $STATUS 1>/dev/null && display_muted || display_unmuted;;
	1) amixer set Master 5%+ && pkill -RTMIN+5 dwmblocks || notify-send "An error ocurred" ;;
	0) amixer set Master 5%- && pkill -RTMIN+5 dwmblocks || notify-send "An error ocurred" ;;
	-1) amixer -D pulse set Master 1+ toggle;
		amixer | grep off && mute_notify || unmute_notify ;;
esac
